AllCops:
  TargetRubyVersion: 2.3

  Include:
    - 'lib/**/*'

  Exclude:
    - Rakefile
    - spec/spec_helper.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Documentation:
  Enabled: false
