AllCops:
  TargetRubyVersion: 2.3

  Include:
    - 'lib/**/*'

  Exclude:
    - Gemfile
    - Rakefile
    - lib/rodolfo/templates/*
    - spec/spec_helper.rb
    - tmp/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 50
